### PR TITLE
rename Codecs -> Decco_Codecs

### PR DESCRIPTION
**Pull request by idkjs**
I have changed the name of of `src/Codecs.re` to `src/Decco_Codecs.re` changed the include statement on here:
https://github.com/reasonml-labs/decco/blob/7161724a18e5d702e071f5b302a1072551580194/src/Decco.re#L149

to:

https://github.com/idkjs/decco/blob/330a903c69dbe4b866fa4429281439c8cc8e836a/src/Decco.re#L149

All tests passed. Not sure if this what you were looking for. Feedback is appreciated. Thank you.

### CODE REVIEW

**Comment by mrmurphy** [comment]
LGTM, @ryb73?

**Comment by mrmurphy** [comment]
Thank you @idkjs!

**Comment by idkjs** [comment]
@mrmurphy same guy Im talking to on twitter. Just realized.

You are welcome. Thanks for the egghead material.

**Comment by ryb73** [comment]
Thanks @idkjs!

**Pull request merged**
