### PR TITLE
Support OCaml 4.14

### PR DESCRIPTION
**Pull request by mayhewluke**
* Update `ppxlib` to `^0.26.0` to gain OCaml 4.14 support
* Update `ocaml` to `4.14.x` to fix `Migration error: existentials in pattern-matching is not supported before OCaml 4.13` when running the PPX on files with existentials in pattern matching

### CODE REVIEW

**Review by anmonteiro — APPROVED** [review]
Thank you! @ryb73 could we get a new release with this fix?

**Comment by ryb73** [comment]
Hey @mayhewluke, @anmonteiro, thanks for the PR. Unfortunately because Travis doesn't offer a free tier anymore, my CI/CD pipeline is broken and I can no longer build and publish cross-platform binaries. I don't know the best way to proceed, but it seems like it might be best to transition away from publishing pre-built binaries and instead use an npm postinstall hook to build on the client side? @anmonteiro you seem to have more Reason + PPX experience, what do you think?

**Comment by mayhewluke** [comment]
@ryb73 I'm no expert here, so I'll defer to @anmonteiro, but building on the client side would be handy for me. I'm on NixOS, and pre-built binaries don't work for it (unless built with Nix itself), so I have to remember to patch the binary after each npm re-install. Building on the client-side would give a seamless experience on NixOS, but that's only a small subset of the user base, so that may not be a significant consideration here.

**Comment by rolandpeelen** [comment]
@ryb73 - My Lens PPX is heavily inspired by your workflow - I build it using Github Actions, by tagging releases it pushes to NPM.

Perhaps we can use something like that here as well?

https://github.com/rolandpeelen/bs-pancake/tree/master/.github/workflows

The only thing lacking there is Windows support - I don't have access a windows machine here / don't really develop on one so I have no idea on how to deal with it :)

**Comment by rolandpeelen** [comment]
This should fix it: https://github.com/reasonml-labs/decco/pull/85 :)

**Comment by ryb73** [comment]
This PR has been released in v1.6.0. Thanks again @mayhewluke and @rolandpeelen!

**Pull request merged**
